matrix:
  include:
    # Linux / Python 2
    - os: linux
      language: python
      python: "2.7"
      env:
        - CACHE_NAME=linux_py2
      dist: trusty
      sudo: required
    # Linux / Python 3
    - os: linux
      language: python
      python: "3.5"
      env:
        - CACHE_NAME=linux_py3
      dist: trusty
      sudo: required

cache:
  directories:
    - .cache

install:
  - ./ci/travis.sh setup

script:
  - ./ci/travis.sh build

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "oevnqcK1AKqtYg6KuA9VjsrvXLl0qbSjJRWWvqJthXxRobGDdaY7asNexemzogUlqIoeJcbmdmirp3pBTRhEWtxCUZa+/TgQ/0H9nMPT4pPo+7Tsucj3bKMIoXK7PUsomOMjM0QnlzaSk85rnrMzdPrl1d6DuW/V8A5ChsHW1k8="
  draft: true
  file_glob: true
  file:
    - "dist/*.AppImage"
    - "dist/*.tar.gz"
    - "dist/*.whl"
  on:
    tags: true
