language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx

before_install:
  - |
    case "$TRAVIS_OS_NAME" in
    osx)
      brew update &&
      brew install python --framework &&
      brew link --overwrite python &&
      brew install wxpython &&
      true
      ;;
    linux)
      sudo apt-add-repository -y ppa:adamwolf/kicad-trusty-backports &&
      sudo apt-get update -qq &&
      sudo apt-get install -y python-wxgtk3.0 python-xlib &&
      true
      ;;
    esac &&
    python setup.py develop --user --upgrade &&
    # Don't use a more recent version of mock or
    # we run into issues with setuptools and six...
    pip install --user --upgrade 'mock==1.0.1' pytest &&
    true

install: true

script:
  - depth=50; while ! git describe --tag '--match=v[0-9]*'; do depth=$(($depth+10)); git fetch --depth $depth; done
  - python setup.py patch_version
  - python setup.py test
  - |
    case "$TRAVIS_OS_NAME" in
    osx)
      make -C osx &&
      true
      ;;
    linux)
      python setup.py bdist_egg &&
      python setup.py bdist_wheel &&
      true
      ;;
    esac

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: p1QHOgNToBnHht/Y05+Nr2QdWgwxYeGJwWvhkcPUNKh7YC59v2AKkRx5YeRF0sYgXK6VOPcxDmdnZ9+5ztVpgjMrMsIGhckYoLOVkHVRhXEKqmz2A8Ol0pTmrvvmqalufa2+6l414/C2GciK95yoQJIfZGZT4xA6QO5dWx52azAtRZVbyG6oenrOPuCeSfXrE9UslHSBKe4afoBiHNEEDewObys45yjXvU1KXRR9TRdO0wOSi0i+cZKj4Azpm7MeFU1ftkjALYoLYinIe5swhpYTsrJRv/qyQR1ZCougFD+PbECx4OJB4Ssn5xdfqj4IKKi3Ja1q6FUF3I+6jI8+p62e5YHjSWahsUOVbaIkDQcC7jNDuT85BXIH2pZT1mjFIhec9q4ramP30BR/1IgX1WYwGLk9y0XYfoTOsPmohFoX3i9U5CgZrjmuNsRbelxFZadVKqwRpJffw3Iaeu6D6kwtN4hGHpYskTEpxWY0M9uFoVwTTFBk9qCr13nkTeXRz3ERRfan2NWPfj8n2O2gG/NOd0SCG5eofHY1EDj7ciULVLl3KFyxBlTDAzy8xoK8laz+WCJ5dxlM2RV0G3OCdCPfLl+vqzcNk9eTtBBshb7qInfgk+hg7eviOeeCOTVcRjxCQHGAvMB4mVxwKHa+DNRmTInFw0Z/rCdEH5DaWog=
  file_glob: true
  file:
    - "dist/*.dmg"
    - "dist/*.egg"
    - "dist/*.whl"
  on:
    tags: true
    repo: openstenoproject/plover
