language: generic

matrix:
  include:
    # Linux / Python 2
    - os: linux
      env:
        - PYTHON=python2
        - CACHE_NAME=linux_py2
      dist: trusty
      sudo: required
      cache:
        directories:
          - $HOME/.cache/pip
      before_cache:
        - rm -rf $HOME/.cache/pip/log
    # Linux / Python 3
    - os: linux
      env:
        - PYTHON=python3
        - CACHE_NAME=linux_py3
      dist: trusty
      sudo: required
      cache:
        directories:
          - $HOME/.cache/pip
      before_cache:
        - rm -rf $HOME/.cache/pip/log
    # OSX / Python 2
    - os: osx
      env:
        - PYTHON=python2
        - CACHE_NAME=osx_py2
      cache:
        directories:
          - /Users/travis/Library/Caches/pip
      before_cache:
        - rm -rf /Users/travis/Library/Caches/pip/log
    # OSX / Python 3
    - os: osx
      env:
        - PYTHON=python3
        - CACHE_NAME=osx_py3
      cache:
        directories:
          - /Users/travis/Library/Caches/pip
      before_cache:
        - rm -rf /Users/travis/Library/Caches/pip/log

before_install:
  - |
    (
    set -ex
    case "$TRAVIS_OS_NAME" in
    osx)
      python_package=''
      packages=()
      case $PYTHON in
      python2)
        python_package='python'
        packages+=( \
          wxpython \
        )
        ;;
      python3)
        python_package='python3'
        packages+=( \
        )
        ;;
      esac
      brew update
      brew install $python_package --framework
      brew link --overwrite $python_package
      [ -n "$packages" ] && brew install "${packages[@]}"
      ;;
    linux)
      sudo apt-add-repository -y ppa:benoit.pierre/plover
      sudo apt-get update -qq
      packages=(libudev-dev libusb-1.0-0-dev)
      case $PYTHON in
      python2)
        packages+=( \
          cython \
          python-dev \
          python-pip \
          python-pkg-resources \
          python-wheel \
          python-wxgtk3.0 \
          python-xlib \
        )
        ;;
      python3)
        packages+=( \
          cython3 \
          python3-dev \
          python3-pip \
          python3-pkg-resources \
          python3-wheel \
          python3-xlib \
        )
        ;;
      esac
      [ -n "$packages" ] && sudo apt-get install -y "${packages[@]}"
      ;;
    esac
    $PYTHON setup.py write_requirements
    pip() { $PYTHON -m pip --disable-pip-version-check --timeout=5 --retries=2 "$@"; }
    # Update antiquated version of pip on Ubuntu...
    $PYTHON -m pip install --upgrade --user pip
    # Upgrade setuptools, we need at least 19.6 to prevent issues with Cython patched 'build_ext' command.
    pip install --upgrade --user 'setuptools>=19.6'
    # Manually install Cython if not already to speedup hidapi build.
    pip install --user Cython
    pip install --upgrade --user -r requirements.txt -c requirements_constraints.txt
    # And now downgrade setuptools so py2app works correctly...
    pip install --upgrade --user 'setuptools==19.2'
    pip list
    )

install: true

script:
  - git fetch --unshallow
  - $PYTHON setup.py patch_version
  - $PYTHON setup.py test

before_deploy:
  - |
    (
    set -ex
    case "$TRAVIS_OS_NAME" in
    osx)
      ;;
    linux)
      $PYTHON setup.py bdist_{egg,wheel}
      ;;
    esac
    # Not all builds will produce artifacts.
    du -hs dist/* || true
    )

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "oevnqcK1AKqtYg6KuA9VjsrvXLl0qbSjJRWWvqJthXxRobGDdaY7asNexemzogUlqIoeJcbmdmirp3pBTRhEWtxCUZa+/TgQ/0H9nMPT4pPo+7Tsucj3bKMIoXK7PUsomOMjM0QnlzaSk85rnrMzdPrl1d6DuW/V8A5ChsHW1k8="
  draft: true
  file_glob: true
  file:
    - "dist/*.dmg"
    - "dist/*.egg"
    - "dist/*.whl"
  on:
    tags: true
