language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx

before_install:
  - |
    case "$TRAVIS_OS_NAME" in
    osx)
      brew update &&
      brew install python --framework &&
      brew link --overwrite python &&
      brew install wxpython &&
      true
      ;;
    linux)
      sudo apt-add-repository -y ppa:adamwolf/kicad-trusty-backports &&
      sudo apt-get update -qq &&
      sudo apt-get install -y cython libudev-dev libusb-1.0-0-dev python-dev python-wxgtk3.0 python-xlib &&
      true
      ;;
    esac &&
    python -c 'import setup; setup.write_requirements()' &&
    pip --disable-pip-version-check --timeout=5 --retries=2 install --upgrade --user -r requirements.txt &&
    # We need to downgrade setuptools for py2app to work correctly...
    pip --disable-pip-version-check --timeout=5 --retries=2 install --upgrade --user 'setuptools==19.2' &&
    pip --disable-pip-version-check list &&
    true

install: true

script:
  - depth=50; while ! git describe --tag '--match=v[0-9]*'; do depth=$(($depth+10)); git fetch --depth $depth; done
  - python setup.py patch_version
  - python setup.py test
  - |
    case "$TRAVIS_OS_NAME" in
    osx)
      make -C osx &&
      true
      ;;
    linux)
      python setup.py bdist_egg &&
      python setup.py bdist_wheel &&
      true
      ;;
    esac

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "shMJ+98tAIA+ZvdqZQd/Kd4KIHGj73GGZYf/eVHlU2V6SV6vWEgleiJSHzxLOnjXoG8vx91+RdYPWIKNW/Jqo7TdY/Gdo65thvPfM6vLOUJn9m5HjgGbj684XNAspBFJwO9w1eJrEbMAduuOxKURoVY1DdivQ1C1dhElzSVsddY="
  file_glob: true
  file:
    - "dist/*.dmg"
    - "dist/*.egg"
    - "dist/*.whl"
  on:
    tags: true
    repo: benoit-pierre/plover
