#!/usr/bin/env python2

from kinglet import system

LETTERS = system.KEYS

IMPLICIT_HYPHEN_LETTERS = system.IMPLICIT_HYPHEN_KEYS

SUFFIX_LETTERS = system.SUFFIX_KEYS

NUMBER_LETTER = system.NUMBER_KEY

NUMBERS = system.NUMBERS

UNDO_STROKE_STENO = system.UNDO_STROKE_STENO

ORTHOGRAPHY_RULES = system.ORTHOGRAPHY_RULES

ORTHOGRAPHY_RULES_ALIASES = system.ORTHOGRAPHY_RULES_ALIASES

ORTHOGRAPHY_WORDLIST = system.ORTHOGRAPHY_WORDLIST

KEYBOARD_KEYMAP = system.KEYBOARD_KEYMAP

